sudo: true

language: python

python:
  - 2.7
# command to install dependencies
install:
  - pip install dronekit dronekit-sitl
script:
  
# command to run tests
# or py.test for Python versions 3.5 and below