sudo: true

language: python

python:
  - 2.7
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
    sh setup.sh
  
# command to run tests
# or py.test for Python versions 3.5 and below
